name: eclectic group
favicon: null
layout_spectrum: 0.654206097824499
typography_spectrum: 0.3096513298805803
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3548579323105514
  lightness: 0.13503787317313254
  saturation: 0.41121712140738964
  rhythmicContrast: 0.06164746405556798
purpose: []
